### ISSUE TITLE
Node description support display link like github

### ISSUE THREAD

**Issue by SpenserCai** [Comfy-Org/registry-backend#90]
The description of the node information can display the supported links in Github. This issue should be submitted to the frontend project, but I haven't found it yet, so I submitted it here.
![image](https://github.com/user-attachments/assets/f0809316-8c66-441c-9283-8fb7d2bf8786)
![image](https://github.com/user-attachments/assets/f17c5783-0cb6-4275-9b75-1b74a9942e21)

**Comment by james03160927** [comment]
Hi @SpenserCai, here is the repository for the registry web - https://github.com/Comfy-Org/registry-web.
